name: tenant specific infra setup

on:
  workflow_dispatch:
    inputs:
      client_name:
        type: choice
        description: Tenant name to setup the infra
        options: 
        - xyz
        - abc_client

#defaults:
#  run:
#    working-directory: dedicated_resources
        
env: 
  S3_TFVARS_FILE: "test"
      
jobs:
  deploy-infra:

    runs-on: ubuntu-18.04
    
    steps:
    - name: checkout code
      uses: actions/checkout@v2
      
    - name: fetch tfvars file
      run: |
        echo "aws s3 cp s3://${S3_TFVARS_FILE}/${{ github.event.inputs.client_name }}.tfvar"
      
    - name: setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.13.0

    - name: terraform fmt
      id: fmt
      run: terraform fmt -check -recursive -no-color .
      continue-on-error: true

   # - name: terraform init
   #   id: init
   #   run: terraform init -no-color
   
    - name: select workspace
      run: |
        terraform workspace list | grep -w "${{ github.event.inputs.client_name }}"

        if [ $? == 0 ]
        then
          terraform workspace select ${{ github.event.inputs.client_name }}
        else
          terraform workspace new ${{ github.event.inputs.client_name }}
        fi
        
    - name: list workspaces
      run: terraform workspace list    

    - name: terraform validate
      id: validate
      run: terraform validate -no-color
      
    - name: terraform plan
      id: plan
      run: echo "terraform plan --var 'client=${{ github.event.inputs.client_name }}'"
