name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        options:
        - foo
        - bar
        - baz
      boolean:
        type: boolean
        description: True or False
      choice:
        type: choice
        description: Select client name to deploy the infra
        options:
        - foo
        - bar
        - baz
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "choice is ${{ github.event.inputs.choice }}"
