name: multi-tenant-terraform-automation

#defaults:
#  run:
#    working-directory: 
on:
  workflow_dispatch:
    inputs:
      client_name:
        type: choice
        description: Choose a client to deploy the infra
        options:
        - test_client
        - common_resource

jobs:
  terraform:

    runs-on: ubuntu-18.04

    steps:
    - name: checkout code
      uses: actions/checkout@v2

   
    - name: setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.13.0

    - name: terraform fmt
      id: fmt
      run: terraform fmt -check -recursive -no-color .
      continue-on-error: true

    - name: terraform validate
      id: validate
      run: terraform validate -no-color
